# -----------------------------
# 1) Build do frontend (Vite)
# -----------------------------
FROM node:22-bullseye AS build

WORKDIR /app

# Copia dependências
COPY package*.json ./

# Instala pacotes
RUN npm install --no-audit --progress=false

# Copia código do projeto
COPY . .

# Gera build estático
RUN npm run build


# -----------------------------
# 2) Servindo com NGINX
# -----------------------------
FROM nginx:stable

# Remove site default
RUN rm -rf /usr/share/nginx/html/*

# Copia o build gerado pelo Vite
COPY --from=build /app/dist /usr/share/nginx/html

# Copia configuração customizada do Nginx
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
