FROM node:22-bullseye

WORKDIR /usr/src/app

# Copia package.json e lock (se existir)
COPY package*.json ./

# Instala dependências
RUN npm install --no-audit --progress=false

# Copia código do backend
COPY . .

# Garante que diretório do banco existe
RUN mkdir -p /data

# Copia entrypoint personalizado
COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

EXPOSE 3000

ENTRYPOINT ["/entrypoint.sh"]
